"""create the course table

Revision ID: 44840537b220
Revises: 
Create Date: 2018-07-20 03:39:27.622532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44840537b220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.SmallInteger(), nullable=True),
    sa.Column('elected', sa.SmallInteger(), nullable=True),
    sa.Column('teacher', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=32), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('schedule', sa.String(length=256), nullable=True),
    sa.Column('schedule_id', sa.String(length=9), nullable=False),
    sa.Column('enroll', sa.Enum('', '内招生', '外招生'), nullable=True),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('exam_typ', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
